# Generated by Django 4.1.5 on 2023-01-29 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_filmwork_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='film_works',
            field=models.ManyToManyField(through='movies.PersonFilmwork', to='movies.filmwork'),
        ),
        migrations.AlterField(
            model_name='personfilmwork',
            name='role',
            field=models.TextField(choices=[('actor', 'Актер'), ('director', 'Режиссер'), ('writer', 'Сценарист')], null=True, verbose_name='Role'),
        ),
    ]
