# Generated by Django 4.1.5 on 2023-02-01 17:51

from django.db import migrations, models


def replace_nulls(apps, schema_editor):
    PersonFilmwork = apps.get_model("movies", "PersonFilmwork")
    PersonFilmwork.objects.filter(role=None).update(role="actor")

    FilmWork = apps.get_model("movies", "FilmWork")
    FilmWork.objects.filter(file_path=None).update(file_path="")


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0003_person_film_works_role_choices"),
    ]

    operations = [
        migrations.RunPython(replace_nulls, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="filmwork",
            name="file_path",
            field=models.TextField(blank=True, verbose_name="File path"),
        ),
        migrations.AlterField(
            model_name="personfilmwork",
            name="role",
            field=models.TextField(
                choices=[
                    ("actor", "Актер"),
                    ("director", "Режиссер"),
                    ("writer", "Сценарист"),
                ],
                verbose_name="Role",
            ),
        ),
    ]
