# Generated by Django 4.1.5 on 2023-02-01 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_removed_null_true'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            DROP INDEX IF EXISTS content.genre_film_work_idx;
            DROP INDEX IF EXISTS content.person_film_work_idx;
            DROP INDEX IF EXISTS content.film_work_creation_rate_idx;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterUniqueTogether(
            name='genrefilmwork',
            unique_together={('genre', 'film_work')},
        ),
        migrations.AlterUniqueTogether(
            name='personfilmwork',
            unique_together={('person', 'film_work', 'role')},
        ),
        migrations.AddIndex(
            model_name='filmwork',
            index=models.Index(fields=['creation_date', 'rating'], name='film_work_creation_rate_idx'),
        ),
        migrations.AddIndex(
            model_name='genrefilmwork',
            index=models.Index(fields=['genre_id', 'film_work_id'], name='genre_film_work_idx'),
        ),
        migrations.AddIndex(
            model_name='personfilmwork',
            index=models.Index(fields=['person_id', 'film_work_id', 'role'], name='person_film_work_idx'),
        ),
    ]
